# Generated by Django 5.2.11 on 2026-02-13 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
