# Generated by Django 5.2.11 on 2026-02-13 18:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_alter_publicacao_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
