# Generated by Django 5.2.11 on 2026-02-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licao',
            options={'verbose_name': 'Lição', 'verbose_name_plural': 'Lições'},
        ),
        migrations.AddField(
            model_name='licao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_licoes/'),
        ),
    ]
