# Generated by Django 5.2.11 on 2026-02-11 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_alter_licao_options_licao_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licao',
            options={'ordering': ['data_lancamento'], 'verbose_name': 'Lição', 'verbose_name_plural': 'Lições'},
        ),
        migrations.AddField(
            model_name='licao',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='atividades/'),
        ),
        migrations.AddField(
            model_name='licao',
            name='data_lancamento',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data que a aula será liberada para os alunos'),
        ),
    ]
