# Generated by Django 5.2.11 on 2026-02-12 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_alter_licao_options_licao_arquivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='data_lancamento',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data que a aula será liberada'),
        ),
    ]
