# Generated by Django 5.2.11 on 2026-02-13 20:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_alter_licao_data_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
