# Generated by Django 5.2.11 on 2026-04-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_alter_licao_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='licao',
            name='conteudo_ia',
            field=models.TextField(blank=True, help_text='Cole aqui o texto da aula para o Mascote IA usar como base.', null=True),
        ),
    ]
