# Generated by Django 5.2.11 on 2026-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0006_licao_conteudo_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Recado')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar o recado do site sem precisar apagar.')),
            ],
            options={
                'verbose_name': 'Recado',
                'verbose_name_plural': 'Recados',
            },
        ),
    ]
